//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjConcept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNote
    {
        public int NoteId { get; set; }
        public string UserId { get; set; }
        public string Note { get; set; }
        public System.DateTime NoteLastUpdate { get; set; }
        public string NoteTitle { get; set; }
    }
}
